"""The Desktop capabilities that system actions drive."""

from typing import Protocol


class DesktopShell(Protocol):
    """The Desktop capabilities that system actions drive."""

    def open_network_overlay(self) -> None: ...
    def open_notifications_overlay(self) -> None: ...
    def open_drm_check(self) -> None: ...
    def pause(self) -> None: ...
