"""The Qt-side Desktop operations the shell coordinators drive."""

from collections.abc import Callable
from typing import Protocol


class DesktopView(Protocol):
    """The Qt-side operations the app-lifecycle coordinator drives on the
    Desktop window. Keeps `AppLifecycle` free of QWidget/QDialog internals: the
    coordinator orchestrates show/hide/activate and dialog spawning through this
    narrow port, and a fake satisfying it makes the lifecycle testable."""

    def is_visible(self) -> bool: ...
    def show_fullscreen(self) -> None: ...
    def activate(self) -> None: ...
    def hide_view(self) -> None: ...
    def close_active_dialog(self) -> None: ...
    def show_confirm(
        self,
        question: str,
        on_confirmed: Callable[[], None],
        on_cancelled: Callable[[], None] | None = None,
    ) -> None: ...
    def show_error(self, message: str) -> None: ...
    # Driven by the Desktop coordinator (show/pause/resume orchestration):
    def take_input(self) -> None: ...      # take gamepad focus (push pad handler)
    def release_input(self) -> None: ...   # give it up (pop pad handler)
    def refresh_windows(self) -> None: ...
    def pause_overlays(self) -> None: ...
    def resume_overlays(self) -> None: ...
