"""The app-control port the Application controller drives — restoring, closing and
querying the foreground app."""

from typing import Protocol

from domain.catalog.target import Target


class AppControl(Protocol):
    """Foreground-app control as the Application controller drives it."""

    def current_app(self) -> Target | None: ...
    def restore_app(self, target: Target) -> None: ...
    def request_close_app(self, target: Target) -> None: ...
    def foreground_pid(self) -> int | None: ...
    def foreground_game_pid(self) -> int | None: ...
    def foreground_is_game(self) -> bool: ...
