"""The window-management port as the lifecycle drives it (KWinWindowManager)."""

from typing import Protocol

from domain.catalog.window import Window


class WindowManager(Protocol):
    """Window management as the lifecycle drives it (KWinWindowManager)."""

    def activate_window(self, window_id: str) -> None: ...
    def close_window(self, window_id: str) -> None: ...
    def cached_windows(self) -> list[Window]: ...
    def refresh_now(self) -> None: ...
    def raise_windows_for_pid_exact(self, pid: int) -> None: ...
    def activate_windows_for_pids(self, pids: set[int]) -> None: ...
    def minimize_windows_for_pids(self, pids: set[int]) -> None: ...
