"""
Obsługa miniatur zgodna z FreeDesktop Thumbnail Specification.
Thumbnail support compliant with FreeDesktop Thumbnail Specification
Searches for ready-made thumbnails from the KDE/tumbler cache and requests them
generated by D-Bus (org.freedesktop.thumbnails.Thumbnailer1).
"""

import hashlib
import mimetypes
from pathlib import Path

from PyQt6.QtCore import QObject, pyqtSignal

try:
    from PyQt6.QtDBus import QDBusConnection, QDBusInterface
    _DBUS_AVAILABLE = True
except ImportError:
    _DBUS_AVAILABLE = False


_THUMB_DIRS = [
    Path.home() / ".cache/thumbnails/large",
    Path.home() / ".cache/thumbnails/normal",
]

_SERVICE   = "org.freedesktop.thumbnails.Thumbnailer1"
_PATH      = "/org/freedesktop/thumbnails/Thumbnailer1"
_INTERFACE = "org.freedesktop.thumbnails.Thumbnailer1"


def is_image(path: Path) -> bool:
    mime, _ = mimetypes.guess_type(str(path))
    return mime is not None and mime.startswith("image/")


def find_thumbnail(path: Path) -> Path | None:
    """
    Returns a path to the current thumbnail if it exists, None otherwise.
    Checks large → normal, validated Thumb::MTime from the PNG header.
    """
    uri = path.as_uri()
    md5 = hashlib.md5(uri.encode()).hexdigest()
    for thumb_dir in _THUMB_DIRS:
        thumb = thumb_dir / f"{md5}.png"
        if not thumb.exists():
            continue
        try:
            actual_mtime = int(path.stat().st_mtime)
        except OSError:
            return None
        thumb_mtime = _read_png_mtime(thumb)
        if thumb_mtime is None or thumb_mtime == actual_mtime:
            return thumb
    return None


def _read_png_mtime(thumb: Path) -> int | None:
    """Reads Thumb::MTime from tEXt chunk of PNG file."""
    try:
        with thumb.open("rb") as f:
            if f.read(8) != b"\x89PNG\r\n\x1a\n":
                return None
            while True:
                raw = f.read(4)
                if len(raw) < 4:
                    return None
                length = int.from_bytes(raw, "big")
                chunk_type = f.read(4)
                data = f.read(length)
                f.read(4)  # CRC
                if chunk_type == b"tEXt":
                    key, _, value = data.partition(b"\x00")
                    if key == b"Thumb::MTime":
                        return int(value)
                elif chunk_type == b"IDAT":
                    return None
    except Exception:
        return None


class Thumbnailer(QObject):
    """
    D-Bus wrapper for org.freedesktop.thumbnails.Thumbnailer1.
    Emits the ready(list[str]) signal with a URI list of ready to use thumbnails.
    """

    ready = pyqtSignal(list)

    def __init__(self, parent: QObject | None = None):
        super().__init__(parent)
        self._iface = self._connect()

    @property
    def available(self) -> bool:
        return self._iface is not None and self._iface.isValid()

    def request(self, uris: list[str], mimes: list[str], flavor: str = "large") -> None:
        """Requests the thumbnail generation for given URIs."""
        if self.available:
            self._iface.call("Queue", uris, mimes, flavor, "default", 0)

    def _connect(self) -> "QDBusInterface | None":
        if not _DBUS_AVAILABLE:
            return None
        bus = QDBusConnection.sessionBus()
        iface = QDBusInterface(_SERVICE, _PATH, _INTERFACE, bus)
        if not iface.isValid():
            return None
        bus.connect(_SERVICE, _PATH, _INTERFACE, "Ready", self._on_ready)
        return iface

    def _on_ready(self, handle, uris) -> None:
        self.ready.emit(list(uris))
