"""The gamepad-control port the lifecycle seizes and cedes."""

from collections.abc import Callable
from typing import Protocol


class PadControl(Protocol):
    """Gamepad input control the lifecycle seizes/cedes (GamepadWatcher): the
    handler stack, the per-app BTN_MODE trigger, a keyboard-driven BTN_MODE
    request, and device re-binding."""

    def set_app_btn_mode_trigger(self, trigger: str) -> None: ...
    def push_handler(self, handler: Callable[[str], None]) -> None: ...
    def pop_handler(self, handler: Callable[[str], None]) -> None: ...
    def top_handler(self) -> Callable[[str], None] | None: ...
    def trigger_btn_mode(self) -> None: ...
    def refresh(self) -> None: ...
    def inject(self, event: str) -> None: ...
